# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftCiqsModelsGalleryPerson(Model):
    """MicrosoftCiqsModelsGalleryPerson.

    :param display_name:
    :type display_name: str
    :param email:
    :type email: str
    :param object_id:
    :type object_id: str
    """

    _attribute_map = {
        'display_name': {'key': 'displayName', 'type': 'str'},
        'email': {'key': 'email', 'type': 'str'},
        'object_id': {'key': 'objectId', 'type': 'str'},
    }

    def __init__(self, display_name=None, email=None, object_id=None):
        super(MicrosoftCiqsModelsGalleryPerson, self).__init__()
        self.display_name = display_name
        self.email = email
        self.object_id = object_id
