# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftCiqsModelsDeploymentCreateDeploymentRequest(Model):
    """MicrosoftCiqsModelsDeploymentCreateDeploymentRequest.

    :param name:
    :type name: str
    :param template_id:
    :type template_id: str
    :param template_variant:
    :type template_variant: str
    :param subscription:
    :type subscription: str
    :param location:
    :type location: str
    :param description:
    :type description: str
    :param referrer:
    :type referrer: str
    :param parameters:
    :type parameters: dict[str, str]
    :param solution_storage_connection_string:
    :type solution_storage_connection_string: str
    :param environment:
    :type environment: str
    """

    _validation = {
        'name': {'required': True},
        'location': {'required': True},
    }

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'template_id': {'key': 'templateId', 'type': 'str'},
        'template_variant': {'key': 'templateVariant', 'type': 'str'},
        'subscription': {'key': 'subscription', 'type': 'str'},
        'location': {'key': 'location', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'referrer': {'key': 'referrer', 'type': 'str'},
        'parameters': {'key': 'parameters', 'type': '{str}'},
        'solution_storage_connection_string': {'key': 'solutionStorageConnectionString', 'type': 'str'},
        'environment': {'key': 'environment', 'type': 'str'},
    }

    def __init__(self, name, location, template_id=None, template_variant=None, subscription=None, description=None, referrer=None, parameters=None, solution_storage_connection_string=None, environment=None):
        super(MicrosoftCiqsModelsDeploymentCreateDeploymentRequest, self).__init__()
        self.name = name
        self.template_id = template_id
        self.template_variant = template_variant
        self.subscription = subscription
        self.location = location
        self.description = description
        self.referrer = referrer
        self.parameters = parameters
        self.solution_storage_connection_string = solution_storage_connection_string
        self.environment = environment
