# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftCiqsModelsDeploymentDeployment(Model):
    """MicrosoftCiqsModelsDeploymentDeployment.

    :param unique_id:
    :type unique_id: str
    :param name:
    :type name: str
    :param template_id:
    :type template_id: str
    :param template_variant:
    :type template_variant: str
    :param template_title:
    :type template_title: str
    :param gallery_url:
    :type gallery_url: str
    :param subscription:
    :type subscription: str
    :param location:
    :type location: str
    :param date_created:
    :type date_created: datetime
    :param date_last_modified:
    :type date_last_modified: datetime
    :param status: Possible values include: 'Created', 'ActionRequired',
     'ParametersSubmitted', 'Provisioning', 'Ready', 'Failed', 'Timeout',
     'Deleting', 'Deleted', 'DeletionFailed', 'Interrupted'
    :type status: str or
     ~microsoft.swagger.codegen.cloudintelligencequickstart.models.enum
    :param description:
    :type description: str
    :param created_by_user_email:
    :type created_by_user_email: str
    :param created_by_user_friendly_name:
    :type created_by_user_friendly_name: str
    :param serialized_operation_status:
    :type serialized_operation_status: str
    :param current_provisioning_step:
    :type current_provisioning_step: int
    :param is_custom_solution:
    :type is_custom_solution: bool
    :param is_orphaned_deployment:
    :type is_orphaned_deployment: bool
    :param is_delete_requested:
    :type is_delete_requested: bool
    :param post_deployment_guidance:
    :type post_deployment_guidance:
     list[~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsGalleryLink]
    :param output_links:
    :type output_links:
     list[~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsGalleryLink]
    :param related_links:
    :type related_links:
     list[~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsGalleryLink]
    :param is_deployed_to_existing_resource_group:
    :type is_deployed_to_existing_resource_group: bool
    :param parameters:
    :type parameters: dict[str, str]
    :param is_imml_ads_user:
    :type is_imml_ads_user: bool
    :param url_referrer:
    :type url_referrer: str
    :param environment:
    :type environment: str
    :param tag_guid:
    :type tag_guid: str
    :param email_templates:
    :type email_templates:
     list[~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsEmailTemplate]
    """

    _attribute_map = {
        'unique_id': {'key': 'uniqueId', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'template_id': {'key': 'templateId', 'type': 'str'},
        'template_variant': {'key': 'templateVariant', 'type': 'str'},
        'template_title': {'key': 'templateTitle', 'type': 'str'},
        'gallery_url': {'key': 'galleryUrl', 'type': 'str'},
        'subscription': {'key': 'subscription', 'type': 'str'},
        'location': {'key': 'location', 'type': 'str'},
        'date_created': {'key': 'dateCreated', 'type': 'iso-8601'},
        'date_last_modified': {'key': 'dateLastModified', 'type': 'iso-8601'},
        'status': {'key': 'status', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'created_by_user_email': {'key': 'createdByUserEmail', 'type': 'str'},
        'created_by_user_friendly_name': {'key': 'createdByUserFriendlyName', 'type': 'str'},
        'serialized_operation_status': {'key': 'serializedOperationStatus', 'type': 'str'},
        'current_provisioning_step': {'key': 'currentProvisioningStep', 'type': 'int'},
        'is_custom_solution': {'key': 'isCustomSolution', 'type': 'bool'},
        'is_orphaned_deployment': {'key': 'isOrphanedDeployment', 'type': 'bool'},
        'is_delete_requested': {'key': 'isDeleteRequested', 'type': 'bool'},
        'post_deployment_guidance': {'key': 'postDeploymentGuidance', 'type': '[MicrosoftCiqsModelsGalleryLink]'},
        'output_links': {'key': 'outputLinks', 'type': '[MicrosoftCiqsModelsGalleryLink]'},
        'related_links': {'key': 'relatedLinks', 'type': '[MicrosoftCiqsModelsGalleryLink]'},
        'is_deployed_to_existing_resource_group': {'key': 'isDeployedToExistingResourceGroup', 'type': 'bool'},
        'parameters': {'key': 'parameters', 'type': '{str}'},
        'is_imml_ads_user': {'key': 'isImmlAdsUser', 'type': 'bool'},
        'url_referrer': {'key': 'urlReferrer', 'type': 'str'},
        'environment': {'key': 'environment', 'type': 'str'},
        'tag_guid': {'key': 'tagGuid', 'type': 'str'},
        'email_templates': {'key': 'emailTemplates', 'type': '[MicrosoftCiqsModelsEmailTemplate]'},
    }

    def __init__(self, unique_id=None, name=None, template_id=None, template_variant=None, template_title=None, gallery_url=None, subscription=None, location=None, date_created=None, date_last_modified=None, status=None, description=None, created_by_user_email=None, created_by_user_friendly_name=None, serialized_operation_status=None, current_provisioning_step=None, is_custom_solution=None, is_orphaned_deployment=None, is_delete_requested=None, post_deployment_guidance=None, output_links=None, related_links=None, is_deployed_to_existing_resource_group=None, parameters=None, is_imml_ads_user=None, url_referrer=None, environment=None, tag_guid=None, email_templates=None):
        super(MicrosoftCiqsModelsDeploymentDeployment, self).__init__()
        self.unique_id = unique_id
        self.name = name
        self.template_id = template_id
        self.template_variant = template_variant
        self.template_title = template_title
        self.gallery_url = gallery_url
        self.subscription = subscription
        self.location = location
        self.date_created = date_created
        self.date_last_modified = date_last_modified
        self.status = status
        self.description = description
        self.created_by_user_email = created_by_user_email
        self.created_by_user_friendly_name = created_by_user_friendly_name
        self.serialized_operation_status = serialized_operation_status
        self.current_provisioning_step = current_provisioning_step
        self.is_custom_solution = is_custom_solution
        self.is_orphaned_deployment = is_orphaned_deployment
        self.is_delete_requested = is_delete_requested
        self.post_deployment_guidance = post_deployment_guidance
        self.output_links = output_links
        self.related_links = related_links
        self.is_deployed_to_existing_resource_group = is_deployed_to_existing_resource_group
        self.parameters = parameters
        self.is_imml_ads_user = is_imml_ads_user
        self.url_referrer = url_referrer
        self.environment = environment
        self.tag_guid = tag_guid
        self.email_templates = email_templates
