# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftCiqsModelsDeploymentDeploymentDetails(Model):
    """MicrosoftCiqsModelsDeploymentDeploymentDetails.

    :param deployment:
    :type deployment:
     ~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsDeploymentDeployment
    :param provisioning_log:
    :type provisioning_log:
     list[~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsDeploymentProvisioningLog]
    :param provisioning_steps:
    :type provisioning_steps:
     list[~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsDeploymentDeploymentProvisioningStep]
    :param variables:
    :type variables: dict[str, str]
    """

    _attribute_map = {
        'deployment': {'key': 'deployment', 'type': 'MicrosoftCiqsModelsDeploymentDeployment'},
        'provisioning_log': {'key': 'provisioningLog', 'type': '[MicrosoftCiqsModelsDeploymentProvisioningLog]'},
        'provisioning_steps': {'key': 'provisioningSteps', 'type': '[MicrosoftCiqsModelsDeploymentDeploymentProvisioningStep]'},
        'variables': {'key': 'variables', 'type': '{str}'},
    }

    def __init__(self, deployment=None, provisioning_log=None, provisioning_steps=None, variables=None):
        super(MicrosoftCiqsModelsDeploymentDeploymentDetails, self).__init__()
        self.deployment = deployment
        self.provisioning_log = provisioning_log
        self.provisioning_steps = provisioning_steps
        self.variables = variables
