# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftCiqsModelsEmailTemplate(Model):
    """MicrosoftCiqsModelsEmailTemplate.

    :param name:
    :type name: str
    :param event_id:
    :type event_id: str
    :param parameters:
    :type parameters:
     list[~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsEmailParameter]
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'event_id': {'key': 'eventId', 'type': 'str'},
        'parameters': {'key': 'parameters', 'type': '[MicrosoftCiqsModelsEmailParameter]'},
    }

    def __init__(self, name=None, event_id=None, parameters=None):
        super(MicrosoftCiqsModelsEmailTemplate, self).__init__()
        self.name = name
        self.event_id = event_id
        self.parameters = parameters
