# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftCiqsModelsProvisioningStepsAzureResourceList(Model):
    """MicrosoftCiqsModelsProvisioningStepsAzureResourceList.

    :param resource_group_name:
    :type resource_group_name: str
    :param subscription:
    :type subscription: str
    :param exclusion_list:
    :type exclusion_list: list[str]
    :param inclusion_list:
    :type inclusion_list: list[str]
    """

    _attribute_map = {
        'resource_group_name': {'key': 'resourceGroupName', 'type': 'str'},
        'subscription': {'key': 'subscription', 'type': 'str'},
        'exclusion_list': {'key': 'exclusionList', 'type': '[str]'},
        'inclusion_list': {'key': 'inclusionList', 'type': '[str]'},
    }

    def __init__(self, resource_group_name=None, subscription=None, exclusion_list=None, inclusion_list=None):
        super(MicrosoftCiqsModelsProvisioningStepsAzureResourceList, self).__init__()
        self.resource_group_name = resource_group_name
        self.subscription = subscription
        self.exclusion_list = exclusion_list
        self.inclusion_list = inclusion_list
