# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftCiqsModelsGalleryParameter(Model):
    """MicrosoftCiqsModelsGalleryParameter.

    :param name:
    :type name: str
    :param type:
    :type type: str
    :param description:
    :type description: str
    :param extra_description:
    :type extra_description: str
    :param allowed_values:
    :type allowed_values: list[str]
    :param regex_chain:
    :type regex_chain:
     list[~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsGalleryRegexEntry]
    :param default_value:
    :type default_value: str
    :param hidden:
    :type hidden: bool
    :param regex:
    :type regex: str
    :param category:
    :type category: str
    :param grouped_with:
    :type grouped_with: str
    :param confirm_required:
    :type confirm_required: bool
    :param error_info:
    :type error_info:
     ~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsErrorInfo
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'extra_description': {'key': 'extraDescription', 'type': 'str'},
        'allowed_values': {'key': 'allowedValues', 'type': '[str]'},
        'regex_chain': {'key': 'regexChain', 'type': '[MicrosoftCiqsModelsGalleryRegexEntry]'},
        'default_value': {'key': 'defaultValue', 'type': 'str'},
        'hidden': {'key': 'hidden', 'type': 'bool'},
        'regex': {'key': 'regex', 'type': 'str'},
        'category': {'key': 'category', 'type': 'str'},
        'grouped_with': {'key': 'groupedWith', 'type': 'str'},
        'confirm_required': {'key': 'confirmRequired', 'type': 'bool'},
        'error_info': {'key': 'errorInfo', 'type': 'MicrosoftCiqsModelsErrorInfo'},
    }

    def __init__(self, name=None, type=None, description=None, extra_description=None, allowed_values=None, regex_chain=None, default_value=None, hidden=None, regex=None, category=None, grouped_with=None, confirm_required=None, error_info=None):
        super(MicrosoftCiqsModelsGalleryParameter, self).__init__()
        self.name = name
        self.type = type
        self.description = description
        self.extra_description = extra_description
        self.allowed_values = allowed_values
        self.regex_chain = regex_chain
        self.default_value = default_value
        self.hidden = hidden
        self.regex = regex
        self.category = category
        self.grouped_with = grouped_with
        self.confirm_required = confirm_required
        self.error_info = error_info
