# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftCiqsModelsDeploymentDeploymentProvisioningStepDeploymentProvisioningStepHiddenProperties(Model):
    """MicrosoftCiqsModelsDeploymentDeploymentProvisioningStepDeploymentProvisioningStepHiddenProperties.

    :param type:
    :type type: str
    :param source_pattern_id:
    :type source_pattern_id: str
    :param arm_template_source:
    :type arm_template_source: str
    :param function_name:
    :type function_name: str
    :param function_app_name:
    :type function_app_name: str
    :param function_url:
    :type function_url: str
    :param function_proxy_url:
    :type function_proxy_url: str
    :param function_status_code:
    :type function_status_code:
     ~microsoft.swagger.codegen.cloudintelligencequickstart.models.SystemNullableSystemNetHttpStatusCode
    :param function_output:
    :type function_output: str
    :param auto_resolve_parameters:
    :type auto_resolve_parameters: bool
    """

    _attribute_map = {
        'type': {'key': 'type', 'type': 'str'},
        'source_pattern_id': {'key': 'sourcePatternId', 'type': 'str'},
        'arm_template_source': {'key': 'armTemplateSource', 'type': 'str'},
        'function_name': {'key': 'functionName', 'type': 'str'},
        'function_app_name': {'key': 'functionAppName', 'type': 'str'},
        'function_url': {'key': 'functionUrl', 'type': 'str'},
        'function_proxy_url': {'key': 'functionProxyUrl', 'type': 'str'},
        'function_status_code': {'key': 'functionStatusCode', 'type': 'SystemNullableSystemNetHttpStatusCode'},
        'function_output': {'key': 'functionOutput', 'type': 'str'},
        'auto_resolve_parameters': {'key': 'autoResolveParameters', 'type': 'bool'},
    }

    def __init__(self, type=None, source_pattern_id=None, arm_template_source=None, function_name=None, function_app_name=None, function_url=None, function_proxy_url=None, function_status_code=None, function_output=None, auto_resolve_parameters=None):
        super(MicrosoftCiqsModelsDeploymentDeploymentProvisioningStepDeploymentProvisioningStepHiddenProperties, self).__init__()
        self.type = type
        self.source_pattern_id = source_pattern_id
        self.arm_template_source = arm_template_source
        self.function_name = function_name
        self.function_app_name = function_app_name
        self.function_url = function_url
        self.function_proxy_url = function_proxy_url
        self.function_status_code = function_status_code
        self.function_output = function_output
        self.auto_resolve_parameters = auto_resolve_parameters
