# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftCiqsModelsGalleryFunctionDefinition(Model):
    """MicrosoftCiqsModelsGalleryFunctionDefinition.

    :param url:
    :type url: str
    """

    _attribute_map = {
        'url': {'key': 'url', 'type': 'str'},
    }

    def __init__(self, url=None):
        super(MicrosoftCiqsModelsGalleryFunctionDefinition, self).__init__()
        self.url = url
