# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftCiqsModelsProvisioningStepsAzureResourceGroup(Model):
    """MicrosoftCiqsModelsProvisioningStepsAzureResourceGroup.

    :param subscription:
    :type subscription: str
    :param name:
    :type name: str
    """

    _attribute_map = {
        'subscription': {'key': 'subscription', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
    }

    def __init__(self, subscription=None, name=None):
        super(MicrosoftCiqsModelsProvisioningStepsAzureResourceGroup, self).__init__()
        self.subscription = subscription
        self.name = name
