# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftCiqsModelsDeploymentDeploymentProvisioningStep(Model):
    """MicrosoftCiqsModelsDeploymentDeploymentProvisioningStep.

    :param id:
    :type id: str
    :param deployment_id:
    :type deployment_id: str
    :param type:
    :type type: str
    :param input_parameter_values:
    :type input_parameter_values: dict[str, str]
    :param outputs:
    :type outputs: dict[str, object]
    :param properties:
    :type properties: dict[str, object]
    :param user_input_required:
    :type user_input_required: bool
    :param standalone:
    :type standalone: bool
    :param execution_retry_count:
    :type execution_retry_count: int
    :param details_url:
    :type details_url: str
    :param title:
    :type title: str
    :param instructions:
    :type instructions:
     ~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsGalleryContent
    :param parameters:
    :type parameters:
     list[~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsGalleryParameter]
    :param retriable:
    :type retriable: bool
    :param auto_retry_count:
    :type auto_retry_count: int
    :param timeout:
    :type timeout: int
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'deployment_id': {'key': 'deploymentId', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'input_parameter_values': {'key': 'inputParameterValues', 'type': '{str}'},
        'outputs': {'key': 'outputs', 'type': '{object}'},
        'properties': {'key': 'properties', 'type': '{object}'},
        'user_input_required': {'key': 'userInputRequired', 'type': 'bool'},
        'standalone': {'key': 'standalone', 'type': 'bool'},
        'execution_retry_count': {'key': 'executionRetryCount', 'type': 'int'},
        'details_url': {'key': 'detailsUrl', 'type': 'str'},
        'title': {'key': 'title', 'type': 'str'},
        'instructions': {'key': 'instructions', 'type': 'MicrosoftCiqsModelsGalleryContent'},
        'parameters': {'key': 'parameters', 'type': '[MicrosoftCiqsModelsGalleryParameter]'},
        'retriable': {'key': 'retriable', 'type': 'bool'},
        'auto_retry_count': {'key': 'autoRetryCount', 'type': 'int'},
        'timeout': {'key': 'timeout', 'type': 'int'},
    }

    def __init__(self, id=None, deployment_id=None, type=None, input_parameter_values=None, outputs=None, properties=None, user_input_required=None, standalone=None, execution_retry_count=None, details_url=None, title=None, instructions=None, parameters=None, retriable=None, auto_retry_count=None, timeout=None):
        super(MicrosoftCiqsModelsDeploymentDeploymentProvisioningStep, self).__init__()
        self.id = id
        self.deployment_id = deployment_id
        self.type = type
        self.input_parameter_values = input_parameter_values
        self.outputs = outputs
        self.properties = properties
        self.user_input_required = user_input_required
        self.standalone = standalone
        self.execution_retry_count = execution_retry_count
        self.details_url = details_url
        self.title = title
        self.instructions = instructions
        self.parameters = parameters
        self.retriable = retriable
        self.auto_retry_count = auto_retry_count
        self.timeout = timeout
