# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftCiqsModelsGalleryLink(Model):
    """MicrosoftCiqsModelsGalleryLink.

    :param name:
    :type name: str
    :param title:
    :type title: str
    :param url:
    :type url: str
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'title': {'key': 'title', 'type': 'str'},
        'url': {'key': 'url', 'type': 'str'},
    }

    def __init__(self, name=None, title=None, url=None):
        super(MicrosoftCiqsModelsGalleryLink, self).__init__()
        self.name = name
        self.title = title
        self.url = url
