# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftCiqsModelsErrorInfo(Model):
    """MicrosoftCiqsModelsErrorInfo.

    :param code:
    :type code: str
    :param http_code: Possible values include: 'Continue',
     'SwitchingProtocols', 'OK', 'Created', 'Accepted',
     'NonAuthoritativeInformation', 'NoContent', 'ResetContent',
     'PartialContent', 'MultipleChoices', 'Ambiguous', 'MovedPermanently',
     'Moved', 'Found', 'Redirect', 'SeeOther', 'RedirectMethod', 'NotModified',
     'UseProxy', 'Unused', 'TemporaryRedirect', 'RedirectKeepVerb',
     'BadRequest', 'Unauthorized', 'PaymentRequired', 'Forbidden', 'NotFound',
     'MethodNotAllowed', 'NotAcceptable', 'ProxyAuthenticationRequired',
     'RequestTimeout', 'Conflict', 'Gone', 'LengthRequired',
     'PreconditionFailed', 'RequestEntityTooLarge', 'RequestUriTooLong',
     'UnsupportedMediaType', 'RequestedRangeNotSatisfiable',
     'ExpectationFailed', 'UpgradeRequired', 'InternalServerError',
     'NotImplemented', 'BadGateway', 'ServiceUnavailable', 'GatewayTimeout',
     'HttpVersionNotSupported'
    :type http_code: str or
     ~microsoft.swagger.codegen.cloudintelligencequickstart.models.enum
    :param target:
    :type target: str
    :param message:
    :type message: str
    :param details:
    :type details:
     list[~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsErrorInfo]
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'http_code': {'key': 'httpCode', 'type': 'str'},
        'target': {'key': 'target', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
        'details': {'key': 'details', 'type': '[MicrosoftCiqsModelsErrorInfo]'},
    }

    def __init__(self, code=None, http_code=None, target=None, message=None, details=None):
        super(MicrosoftCiqsModelsErrorInfo, self).__init__()
        self.code = code
        self.http_code = http_code
        self.target = target
        self.message = message
        self.details = details
