# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftCiqsModelsDeploymentProvisioningLog(Model):
    """MicrosoftCiqsModelsDeploymentProvisioningLog.

    :param deployment_id:
    :type deployment_id: str
    :param row_key:
    :type row_key: str
    :param timestamp:
    :type timestamp: datetime
    :param provisioning_step:
    :type provisioning_step: int
    :param status: Possible values include: 'Created', 'ActionRequired',
     'ParametersSubmitted', 'Provisioning', 'Ready', 'Failed', 'Timeout',
     'Deleting', 'Deleted', 'DeletionFailed', 'Interrupted'
    :type status: str or
     ~microsoft.swagger.codegen.cloudintelligencequickstart.models.enum
    :param status_code:
    :type status_code: str
    :param message:
    :type message: str
    """

    _attribute_map = {
        'deployment_id': {'key': 'deploymentId', 'type': 'str'},
        'row_key': {'key': 'rowKey', 'type': 'str'},
        'timestamp': {'key': 'timestamp', 'type': 'iso-8601'},
        'provisioning_step': {'key': 'provisioningStep', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'status_code': {'key': 'statusCode', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
    }

    def __init__(self, deployment_id=None, row_key=None, timestamp=None, provisioning_step=None, status=None, status_code=None, message=None):
        super(MicrosoftCiqsModelsDeploymentProvisioningLog, self).__init__()
        self.deployment_id = deployment_id
        self.row_key = row_key
        self.timestamp = timestamp
        self.provisioning_step = provisioning_step
        self.status = status
        self.status_code = status_code
        self.message = message
