# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftCiqsApiModelsExecuteProvisioningStepResponse(Model):
    """MicrosoftCiqsApiModelsExecuteProvisioningStepResponse.

    :param current_provisioning_step: Gets or sets current provisioning step
     index.
    :type current_provisioning_step: int
    :param provisioning_step:
    :type provisioning_step:
     ~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsDeploymentDeploymentProvisioningStep
    :param status: Gets or sets Deployment status. Possible values include:
     'Created', 'ActionRequired', 'ParametersSubmitted', 'Provisioning',
     'Ready', 'Failed', 'Timeout', 'Deleting', 'Deleted', 'DeletionFailed',
     'Interrupted'
    :type status: str or
     ~microsoft.swagger.codegen.cloudintelligencequickstart.models.enum
    """

    _attribute_map = {
        'current_provisioning_step': {'key': 'currentProvisioningStep', 'type': 'int'},
        'provisioning_step': {'key': 'provisioningStep', 'type': 'MicrosoftCiqsModelsDeploymentDeploymentProvisioningStep'},
        'status': {'key': 'status', 'type': 'str'},
    }

    def __init__(self, current_provisioning_step=None, provisioning_step=None, status=None):
        super(MicrosoftCiqsApiModelsExecuteProvisioningStepResponse, self).__init__()
        self.current_provisioning_step = current_provisioning_step
        self.provisioning_step = provisioning_step
        self.status = status
