# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftCiqsModelsProvisioningStepsAadApplication(Model):
    """MicrosoftCiqsModelsProvisioningStepsAadApplication.

    :param application_id:
    :type application_id: str
    """

    _attribute_map = {
        'application_id': {'key': 'applicationId', 'type': 'str'},
    }

    def __init__(self, application_id=None):
        super(MicrosoftCiqsModelsProvisioningStepsAadApplication, self).__init__()
        self.application_id = application_id
