# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftCiqsModelsGalleryTemplate(Model):
    """MicrosoftCiqsModelsGalleryTemplate.

    :param id:
    :type id: str
    :param variant:
    :type variant: str
    :param variant_display:
    :type variant_display: str
    :param category: Possible values include: 'Internal', 'Solution',
     'Tutorial', 'Partial'
    :type category: str or
     ~microsoft.swagger.codegen.cloudintelligencequickstart.models.enum
    :param is_legacy_template:
    :type is_legacy_template: bool
    :param disabled:
    :type disabled: str
    :param title:
    :type title: str
    :param owners:
    :type owners:
     list[~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsGalleryPerson]
    :param register_resource_providers:
    :type register_resource_providers:
     list[~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsGalleryResourceProvider]
    :param owner:
    :type owner:
     ~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsGalleryPerson
    :param image_url:
    :type image_url: str
    :param estimated_time:
    :type estimated_time: str
    :param description:
    :type description: str
    :param ingredients:
    :type ingredients: list[str]
    :param guide:
    :type guide:
     ~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsGalleryGuide
    :param long_description:
    :type long_description: str
    :param post_deployment_guidance_url:
    :type post_deployment_guidance_url: str
    :param try_it_now:
    :type try_it_now:
     ~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsGalleryTryItNow
    :param prerequisites:
    :type prerequisites:
     ~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsGalleryContent
    :param estimated_cost:
    :type estimated_cost:
     ~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsGalleryEstimatedCost
    :param partners_link:
    :type partners_link: str
    :param partners:
    :type partners:
     list[~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsGalleryLink]
    :param tags:
    :type tags: list[str]
    :param feedback:
    :type feedback:
     ~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsGalleryPerson
    :param related_links:
    :type related_links:
     list[~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsGalleryLink]
    :param provisioning_steps:
    :type provisioning_steps:
     list[~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsProvisioningStepsProvisioningStep]
    :param de_provisioning_steps:
    :type de_provisioning_steps:
     ~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsProvisioningStepsDeleteAzureEntities
    :param gallery_url:
    :type gallery_url: str
    :param summary:
    :type summary:
     ~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsGallerySummary
    :param extended_properties:
    :type extended_properties:
     list[~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsGalleryExtendedProperty]
    :param is_default_variant:
    :type is_default_variant: bool
    :param variants:
    :type variants:
     list[~microsoft.swagger.codegen.cloudintelligencequickstart.models.MicrosoftCiqsModelsGalleryTemplate]
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'variant': {'key': 'variant', 'type': 'str'},
        'variant_display': {'key': 'variantDisplay', 'type': 'str'},
        'category': {'key': 'category', 'type': 'str'},
        'is_legacy_template': {'key': 'isLegacyTemplate', 'type': 'bool'},
        'disabled': {'key': 'disabled', 'type': 'str'},
        'title': {'key': 'title', 'type': 'str'},
        'owners': {'key': 'owners', 'type': '[MicrosoftCiqsModelsGalleryPerson]'},
        'register_resource_providers': {'key': 'registerResourceProviders', 'type': '[MicrosoftCiqsModelsGalleryResourceProvider]'},
        'owner': {'key': 'owner', 'type': 'MicrosoftCiqsModelsGalleryPerson'},
        'image_url': {'key': 'imageUrl', 'type': 'str'},
        'estimated_time': {'key': 'estimatedTime', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'ingredients': {'key': 'ingredients', 'type': '[str]'},
        'guide': {'key': 'guide', 'type': 'MicrosoftCiqsModelsGalleryGuide'},
        'long_description': {'key': 'longDescription', 'type': 'str'},
        'post_deployment_guidance_url': {'key': 'postDeploymentGuidanceUrl', 'type': 'str'},
        'try_it_now': {'key': 'tryItNow', 'type': 'MicrosoftCiqsModelsGalleryTryItNow'},
        'prerequisites': {'key': 'prerequisites', 'type': 'MicrosoftCiqsModelsGalleryContent'},
        'estimated_cost': {'key': 'estimatedCost', 'type': 'MicrosoftCiqsModelsGalleryEstimatedCost'},
        'partners_link': {'key': 'partnersLink', 'type': 'str'},
        'partners': {'key': 'partners', 'type': '[MicrosoftCiqsModelsGalleryLink]'},
        'tags': {'key': 'tags', 'type': '[str]'},
        'feedback': {'key': 'feedback', 'type': 'MicrosoftCiqsModelsGalleryPerson'},
        'related_links': {'key': 'relatedLinks', 'type': '[MicrosoftCiqsModelsGalleryLink]'},
        'provisioning_steps': {'key': 'provisioningSteps', 'type': '[MicrosoftCiqsModelsProvisioningStepsProvisioningStep]'},
        'de_provisioning_steps': {'key': 'deProvisioningSteps', 'type': 'MicrosoftCiqsModelsProvisioningStepsDeleteAzureEntities'},
        'gallery_url': {'key': 'galleryUrl', 'type': 'str'},
        'summary': {'key': 'summary', 'type': 'MicrosoftCiqsModelsGallerySummary'},
        'extended_properties': {'key': 'extendedProperties', 'type': '[MicrosoftCiqsModelsGalleryExtendedProperty]'},
        'is_default_variant': {'key': 'isDefaultVariant', 'type': 'bool'},
        'variants': {'key': 'variants', 'type': '[MicrosoftCiqsModelsGalleryTemplate]'},
    }

    def __init__(self, id=None, variant=None, variant_display=None, category=None, is_legacy_template=None, disabled=None, title=None, owners=None, register_resource_providers=None, owner=None, image_url=None, estimated_time=None, description=None, ingredients=None, guide=None, long_description=None, post_deployment_guidance_url=None, try_it_now=None, prerequisites=None, estimated_cost=None, partners_link=None, partners=None, tags=None, feedback=None, related_links=None, provisioning_steps=None, de_provisioning_steps=None, gallery_url=None, summary=None, extended_properties=None, is_default_variant=None, variants=None):
        super(MicrosoftCiqsModelsGalleryTemplate, self).__init__()
        self.id = id
        self.variant = variant
        self.variant_display = variant_display
        self.category = category
        self.is_legacy_template = is_legacy_template
        self.disabled = disabled
        self.title = title
        self.owners = owners
        self.register_resource_providers = register_resource_providers
        self.owner = owner
        self.image_url = image_url
        self.estimated_time = estimated_time
        self.description = description
        self.ingredients = ingredients
        self.guide = guide
        self.long_description = long_description
        self.post_deployment_guidance_url = post_deployment_guidance_url
        self.try_it_now = try_it_now
        self.prerequisites = prerequisites
        self.estimated_cost = estimated_cost
        self.partners_link = partners_link
        self.partners = partners
        self.tags = tags
        self.feedback = feedback
        self.related_links = related_links
        self.provisioning_steps = provisioning_steps
        self.de_provisioning_steps = de_provisioning_steps
        self.gallery_url = gallery_url
        self.summary = summary
        self.extended_properties = extended_properties
        self.is_default_variant = is_default_variant
        self.variants = variants
