# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftCiqsModelsGalleryEstimatedCost(Model):
    """MicrosoftCiqsModelsGalleryEstimatedCost.

    :param daily:
    :type daily: str
    :param url:
    :type url: str
    """

    _attribute_map = {
        'daily': {'key': 'daily', 'type': 'str'},
        'url': {'key': 'url', 'type': 'str'},
    }

    def __init__(self, daily=None, url=None):
        super(MicrosoftCiqsModelsGalleryEstimatedCost, self).__init__()
        self.daily = daily
        self.url = url
