# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftCiqsModelsGalleryOfferPlan(Model):
    """MicrosoftCiqsModelsGalleryOfferPlan.

    :param publisher_id:
    :type publisher_id: str
    :param offer_id:
    :type offer_id: str
    :param plan_id:
    :type plan_id: str
    :param terms_of_use_url:
    :type terms_of_use_url: str
    """

    _attribute_map = {
        'publisher_id': {'key': 'publisherId', 'type': 'str'},
        'offer_id': {'key': 'offerId', 'type': 'str'},
        'plan_id': {'key': 'planId', 'type': 'str'},
        'terms_of_use_url': {'key': 'termsOfUseUrl', 'type': 'str'},
    }

    def __init__(self, publisher_id=None, offer_id=None, plan_id=None, terms_of_use_url=None):
        super(MicrosoftCiqsModelsGalleryOfferPlan, self).__init__()
        self.publisher_id = publisher_id
        self.offer_id = offer_id
        self.plan_id = plan_id
        self.terms_of_use_url = terms_of_use_url
