# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftCiqsModelsGalleryGuide(Model):
    """MicrosoftCiqsModelsGalleryGuide.

    :param format:
    :type format: str
    :param data:
    :type data: str
    """

    _attribute_map = {
        'format': {'key': 'format', 'type': 'str'},
        'data': {'key': 'data', 'type': 'str'},
    }

    def __init__(self, format=None, data=None):
        super(MicrosoftCiqsModelsGalleryGuide, self).__init__()
        self.format = format
        self.data = data
