# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SystemNullableSystemNetHttpStatusCode(Model):
    """SystemNullableSystemNetHttpStatusCode.

    :param has_value:
    :type has_value: bool
    :param value: Possible values include: 'Continue', 'SwitchingProtocols',
     'OK', 'Created', 'Accepted', 'NonAuthoritativeInformation', 'NoContent',
     'ResetContent', 'PartialContent', 'MultipleChoices', 'Ambiguous',
     'MovedPermanently', 'Moved', 'Found', 'Redirect', 'SeeOther',
     'RedirectMethod', 'NotModified', 'UseProxy', 'Unused',
     'TemporaryRedirect', 'RedirectKeepVerb', 'BadRequest', 'Unauthorized',
     'PaymentRequired', 'Forbidden', 'NotFound', 'MethodNotAllowed',
     'NotAcceptable', 'ProxyAuthenticationRequired', 'RequestTimeout',
     'Conflict', 'Gone', 'LengthRequired', 'PreconditionFailed',
     'RequestEntityTooLarge', 'RequestUriTooLong', 'UnsupportedMediaType',
     'RequestedRangeNotSatisfiable', 'ExpectationFailed', 'UpgradeRequired',
     'InternalServerError', 'NotImplemented', 'BadGateway',
     'ServiceUnavailable', 'GatewayTimeout', 'HttpVersionNotSupported'
    :type value: str or
     ~microsoft.swagger.codegen.cloudintelligencequickstart.models.enum
    """

    _attribute_map = {
        'has_value': {'key': 'hasValue', 'type': 'bool'},
        'value': {'key': 'value', 'type': 'str'},
    }

    def __init__(self, has_value=None, value=None):
        super(SystemNullableSystemNetHttpStatusCode, self).__init__()
        self.has_value = has_value
        self.value = value
